version: '3'
services:
  ubuntu:
    build:
        context: .
        dockerfile: ./ubuntu/Dockerfile
    tty: true
    stdin_open: true
    volumes:
        # playgroundディレクトリをコンテナ内/home/playground/と連動させる
        - ./playground:/home/playground